export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
export PATH="/Users/jonghyun/anaconda3/bin/:$PATH"
